# Generated by Django 6.0.7 on 2026-07-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('plot', 'Plot'), ('rental', 'Rental'), ('house', 'House')], max_length=50)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('tagFeatured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
