# Generated by Django 6.0.7 on 2026-08-03 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stat_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
    ]
